### ISSUE TITLE
es6 arrow operator not working

### ISSUE THREAD

**Issue by parinck** [adobe-research/theseus#83]
for code

```
var a = [{_id:123}];
var c = {};
a.forEach((d) => {
    c[d._id] = true;
})
```

Got following error

```
exception during parsing /Users/parinkumar.katariya/apps/elastic/test.js Error: Line 504: Unexpected token >
    at throwError (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:1213:9)
    at parsePrimaryExpression (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:1561:16)
    at /Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:3598:38
    at trackLeftHandSideExpressionAllowCall (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:3493:61)
    at parsePostfixExpression (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:1697:20)
    at /Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:3598:38
    at parseUnaryExpression (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:1777:16)
    at /Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:3598:38
    at parseMultiplicativeExpression (/Users/parinkumar.katariya/.nvm/versions/node/v5.6.0/lib/node_modules/node-theseus/node_modules/esprima/esprima.js:1783:20)
```

**Comment by alltom** [comment]
Unfortunately, Theseus doesn't support the ES6 syntax for that anonymous function yet. We need to upgrade our version of Esprima.

**Comment by CelsoSantos** [comment]
I'm also having this issue.

I'm using ES6 on my node apps and I can't make Theseus work, which is a shame. I was really looking forward to a decent debugger

**Comment by alltom** [comment]
Sorry about that. :\

**Comment by CelsoSantos** [comment]
Not wanting to be one of "those" guys, but is there any estimation of a time frame to get that support? Is that in the current plans?
